goit10/goit10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

goit10/quotes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "quotes"


urlpatterns = [
    path('', views.main, name="root"),
    path('<int:page>', views.main, name="root_paginate"),
    path('author_page/<int:author_id>', views.author_page, name='author_page'),
    path('tag_page/<str:tag>', views.tag_page, name='tag_page'),
    path('users/', include('users.urls')),
    path('nauthor', views.nauthor, name="nauthor"),
    path('nquote', views.nquote, name="nquote"),
]

goit10/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

goit10/quotes/models.py
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

goit10/users/models.py
from django.db import models

# Create your models here.

goit10/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField, Textarea, ChoiceField
from .models import Author, Quote


class AuthorForm(ModelForm):

    fullname = CharField(
        min_length=3, max_length=50, required=True, widget=TextInput()
    )

    born_date = CharField(max_length=50,  widget=TextInput())
    born_location = CharField(max_length=50,  widget=Textarea())
    description = CharField(min_length=10, max_length=150, required=True, widget=Textarea())


    class Meta:
        model = Author
        fields = ['fullname','born_date', 'born_location', 'description']


class AuthorChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.fullname

class QuoteForm(ModelForm):
    author = AuthorChoiceField(queryset=Author.objects.all(), required=True)
    quote = CharField(min_length=10, max_length=150, required=True, widget=Textarea())

    class Meta:
        model = Quote
        fields = ['quote', 'author']

goit10/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

goit10/quotes/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Quote, Author, Tag
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AuthorForm, QuoteForm

def main(request, page=1):
    quotes = Quote.objects.all()

    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})



def nauthor(request):

    if request.method == 'POST':
        form = AuthorForm(request.POST)

        if form.is_valid():

            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/nauthor.html', {'form': form})

    return render(request, 'quotes/nauthor.html', {'form': AuthorForm()})
    # return render(request)

def nquote(request):
    
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')  
    else:
        form = QuoteForm()
    return render(request, 'quotes/nquote.html', {'form': form})
    

def author_page(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotes/author_page.html', {"author": author})

def tag_page(request, tag):
    tag = get_object_or_404(Tag, name=tag)
    # print('---------',tag)
    quotes_with_tag = Quote.objects.filter(tags=tag)
    # print('---///---',quotes_with_tag)
    return render(request, 'quotes/tag_page.html', context={'quotes': quotes_with_tag})

goit10/users/views.py
from django.shortcuts import render, redirect

from .forms import RegisterForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
       return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:root')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:root')

goit10/quotes/templates/quotes/author_page.html
{% extends "quotes/base.html" %}  

{% block content %}

<h1>{{author.fullname}}</h1>
<p><b>Born: </b>{{author.born_date}} {{author.born_location}}</p>
<p><b>Description: </b>{{author.description}}</p>


{% endblock %}

goit10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="Viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>GoIT10</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                
                    <a href="/users/signup" class="btn btn-primary">SignUp</a>
                    <a href="/users/login" class="btn btn-primary">Login</a>
                    <a href="/users/logout" class="btn btn-primary">Logout</a>

                </p> 
            </div>

        </div>
    

        {% block content %}  {% endblock %}

    </div> 
</body>
</html>

goit10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% load extract_a %}

{% block content %}

<div class="row">

    <div class="col-md-8">
        {% if user.is_authenticated %}
        <div class="col-md-8">
            <p>
            <a href="/nauthor" class="btn btn-primary">Аdd a new author</a>
            <a href="/nquote" class="btn btn-primary">Add a new quote</a>
            </p> 
        </div>
        {% endif %}
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author_page/{{quote.author_id}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for stag in quote.id|qtag %}
    
            <a class="tag" href="/tag_page/{{stag}}">{{stag}}</a>
            {% endfor %}
        </div>
        
    </div>



    {% endfor %}
    <nav>
        <ul class="pager">
            
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                    href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>
            
            
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                    href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
            </li>
            
        </ul>
    </nav>
    </div>

</div>

{% endblock %}

goit10/quotes/templates/quotes/nauthor.html
{% extends 'quotes/base.html' %}



{% block content %}

<form method="POST" action="{% url 'quotes:nauthor' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Fullname:       
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>    
    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>


{% endblock %}

goit10/quotes/templates/quotes/nquote.html
{% extends 'quotes/base.html' %}



{% block content %}

<form method="POST" action="{% url 'quotes:nquote' %}">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <div style="padding: 10px">
        <label> Author:       
            {{ form.author }}
        </label>
    </div>
    <div style="padding: 10px">
        <label> Quote:       
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>




{% endblock %}

goit10/quotes/templates/quotes/tag_page.html
{% extends 'quotes/base.html' %}

{% load extract_a %}

{% block content %}

<div class="row">
    <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author_page/{{quote.author_id}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for stag in quote.id|qtag %}
    
            <a class="tag" href="/tag_page/{{stag}}">{{stag}}</a>
            {% endfor %}
        </div>
    </div>


    {% endfor %}

    </div>

</div>

{% endblock %}

goit10/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

goit10/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}
<p>Your password has been set. You can now <a href="{% url 'users:login' %}">log in</a> with the new password.</p>
{% endblock %}

goit10/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}
<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change my password</button>
</form>
{% endblock %}

goit10/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}
<p>An email has been sent with instructions to reset your password.</p>
{% endblock %}

goit10/users/templates/users/password_reset_email.html
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% blocktrans %}Please go to the following page and choose a new password:{% endblocktrans %}
{% blocktrans %}{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}{% endblocktrans %}

{% blocktrans %}Your username, in case you've forgotten: {{ user.get_username }}{% endblocktrans %}

{% blocktrans %}Thanks for using our site!{% endblocktrans %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

goit10/users/templates/users/password_reset_form.html
{% extends "quotes/base.html" %}

{% block content %}
<h2>Reset your password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset my password</button>
</form>
{% endblock %}

goit10/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}